spring.profiles.active: development
---
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.4.63}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: development
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.4.63}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.4.63}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.4.63:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.4.63}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false
